### ISSUE TITLE
Following up dotnet/coreclr/3462

### ISSUE THREAD

**Issue by myungjoo** [myungjoo/coreclr#1]
This is to note in-progress results of https://github.com/dotnet/coreclr/issues/3462

---

Another clue.

```
(gdb) bt
#0  UnwindContextToWinContext (cursor=0xbeffa6c4, winContext=0xbeffe7b8)
    at /usr/src/debug/coreclr-0.0.1/src/pal/src/exception/seh-unwind.cpp:171
#1  0xb6a8c572 in PAL_VirtualUnwind (context=0xbeffe7b8, contextPointers=0x0)
    at /usr/src/debug/coreclr-0.0.1/src/pal/src/exception/seh-unwind.cpp:299
#2  0xb6382c20 in Thread::VirtualUnwindToFirstManagedCallFrame (
    pContext=0xbeffe7b8)
    at /usr/src/debug/coreclr-0.0.1/src/vm/stackwalk.cpp:781
#3  0xb6508b20 in DispatchManagedException (ex=...)
    at /usr/src/debug/coreclr-0.0.1/src/vm/exceptionhandling.cpp:4664
#4  0xb66f0924 in PreStubWorker (pTransitionBlock=0xbeffed1c, pMD=0xb592e8c4)
    at /usr/src/debug/coreclr-0.0.1/src/vm/prestub.cpp:1040
#5  0xb651b66c in ThePreStub () at asmhelpers.S:787
#6  0x0e32e828 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 

```

In the same stack backtrace above, the frame 5 (just one before the managed frame) has

```
(gdb) info frame 5
Stack frame at 0xbeffecfc:
 pc = 0xb651b66c in ThePreStub (asmhelpers.S:787); saved pc = 0xe32e828
 called by frame at 0xbeffecfc, caller of frame at 0xbeffecd8
 source language asm.
 Arglist at 0xbeffecd8, args: 
 Locals at 0xbeffecd8, Previous frame's sp is 0xbeffecfc
 Saved registers:
  r4 at 0xbeffecd8, r5 at 0xbeffecdc, r6 at 0xbeffece0, r7 at 0xbeffece4,
  r8 at 0xbeffece8, r9 at 0xbeffecec, r10 at 0xbeffecf0, r11 at 0xbeffecf4,
  lr at 0xbeffecf8
(gdb) 
```

```
(gdb) p/x *0xbeffecf8
$7 = 0xe32e829
(gdb) info frame 6
Stack frame at 0xbeffecfc:
 pc = 0xe32e828; saved pc = 0xe32e828
 Outermost frame: previous frame identical to this frame (corrupt stack?)
 caller of frame at 0xbeffecfc
 Arglist at 0xbeffecfc, args: 
 Locals at 0xbeffecfc, Previous frame's sp is 0xbeffecfc

```

Why in the hell 3->4->5 works while 5-6 fails (garbages):

Here goes winContext of 6 (5->6)

```
(gdb) p/x winContext
$13 = 0xbeffe7b8
(gdb) p/x *winContext
$14 = {ContextFlags = 0x20000b, R0 = 0xbeffe7b8, R1 = 0xbeffeac0, R2 = 0x0, 
  R3 = 0x1, R4 = 0x20000b, R5 = 0xbeffe7b8, R6 = 0xbeffeac0, R7 = 0x0, 
  R8 = 0x1, R9 = 0x20000b, R10 = 0xbeffe7b8, R11 = 0xbeffeac0, 
  R12 = 0xb6f95424, Sp = 0xbeffe7b8, Lr = 0xbeffed50, Pc = 0xbeffed50, 
  Cpsr = 0x200f0010, Fpscr = 0x80000010, Padding = 0x0, {Q = {{
        Low = 0x10000ffff007d, High = 0x1}, {Low = 0x1, High = 0x1}, {
        Low = 0x1, High = 0x1}, {Low = 0x1, High = 0x1}, {Low = 0x0, 
        High = 0x0}, {Low = 0x0, High = 0x0}, {Low = 0x0, High = 0x0}, {
        Low = 0x0, High = 0x0}, {Low = 0x11, High = 0x0}, {
        Low = 0x3ff4cccccccccccd, High = 0x0}, {Low = 0x0, High = 0x0}, {
        Low = 0x0, High = 0x0}, {Low = 0x0, High = 0x0}, {Low = 0x0, 
        High = 0x0}, {Low = 0x0, High = 0x0}, {Low = 0x0, High = 0x0}}, D = {
      0x10000ffff007d, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 
      0x0, 0x0, 0x0, 0x0, 0x11, 0x0, 0x3ff4cccccccccccd, 
      0x0 <repeats 13 times>}, S = {0xffff007d, 0x10000, 0x1, 0x0, 0x1, 0x0, 
      0x1, 0x0, 0x1, 0x0, 0x1, 0x0, 0x1, 0x0, 0x1, 0x0 <repeats 17 times>}}, 
  Bvr = {0x5d060, 0xbeffe928, 0xb6d3f7f0, 0xb1add045, 0x5d060, 0x0, 
    0xb6e41000, 0x1}, Bcr = {0x5d058, 0x5d058, 0xbeffe948, 0xb62df173, 0x1, 
    0x0, 0xbeffeac0, 0xb1add045}, Wvr = {0xbefff370}, Wcr = {0xbeffecd8}, 
  Padding2 = {0xbeffecd0, 0xb6d2ba94}}


```

**Comment by myungjoo** [comment]
This is (after cleaning the LSB of PC from wincontext) caused by incompatibility (i'd say it's a bug of libunwind-arm for DWARF unwinding) between libunwind-arm and coreclr-arm.

The main cause of the incompatibility (libunwind-arm) is that the fall-back mechanism of DWARF-unwinding is not working because "DWARF unwinding trial function" has a side effect that the data structure given to the fall-back mechanism is modified during the trial. Therefore, the data given to the fall-back mechanism (which is the "primary" mechanism if DWARF is disabled) is not same with the data given to it when DWARF is disabled.

asmhelpers.S's stack frame is not compatible with DWARF, which causes the issue above. The current guess is the availability of "mov r7, sp" before calling a function. (testing with build number 34, 3/3 last build)

Although, some folks have added -g option unconditionally for coreclr build, the compatibility with DWARF needs to be checked again as well.

Even if this is solved by "mov r7, sp" in asmhelpers.S or libunwind environmental variable, ultimately, we will need to remove the side effect of DWARF in libunwind.

For now,... maybe... as Ben Pye has suggested, maybe, we need to just move on with the workaround of setting the environmental variable. But, this should be done in coreclr runtime and we should never assume or require the user to set the environmental variable "correctly".

**Comment by myungjoo** [comment]
I have just sent a patch for libunwind via the mailing list:

```
From 11f97a1be45e435ac0116fedf828063409f5572e Mon Sep 17 00:00:00 2001
From: MyungJoo Ham <myungjoo.ham@samsung.com>
Date: Thu, 25 Feb 2016 10:24:12 +0900
Subject: [PATCH] arm: fix reading SP register read

Partially reverting 0f9937485 while keeping
the part that disallowing writing to SP.

Change-Id: I95a132be03aa1506970aec24ec81906a22bb615d
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>
---
 src/arm/Gregs.c | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/arm/Gregs.c b/src/arm/Gregs.c
index 688771f..0cc5552 100644
--- a/src/arm/Gregs.c
+++ b/src/arm/Gregs.c
@@ -51,6 +51,10 @@ tdep_access_reg (struct cursor *c, unw_regnum_t reg, unw_word_t *valp,
       break;

     case UNW_ARM_R13:
+      if (write)
+        return -UNW_EREADONLYREG;
+      loc = c->dwarf.loc[reg - UNW_ARM_R0];
+      break;
     case UNW_ARM_CFA:
       if (write)
         return -UNW_EREADONLYREG;
-- 
1.9.1

```
