### ISSUE TITLE
Tracking #4589

### ISSUE THREAD

**Issue by myungjoo** [myungjoo/coreclr#7]
1. `isManagedCode` of `HandleHardwareException()` in `src/vm/exceptionhandling.cpp` is `0` where JIT gives null pointer to the assembly native function, `JIT_WriteBarrier`, which actually accesses the pointer given by JIT.
2. DispatchManagedException in that case should catch in its try or go , but reaches to throw ex.

**Comment by myungjoo** [comment]
It thinks there is no managed frames up ahead!
`// There are no managed frames on the stack, so we need to continue unwinding using C++ exception`

**Comment by myungjoo** [comment]
async signal safety?

---

freaking gettid:

```
Catchpoint 2 (call to syscall gettid), syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:38
38      pop {r4, r5, r6, r7}
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:38
#1  0xb6b31428 in GetCurrentThreadId () at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/pal/src/thread/thread.cpp:390
#2  0xb62bde62 in ThreadStressLog::LogMsg (this=0x298e8, facility=16384, cArgs=5, format=0xb6b85463 "Processing exception at establisher=%p, ip=%p disp->cxr: %p, sp: %p, cxr @ exception: %p\n", 
    Args=...) at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/utilcode/stresslog.cpp:580
#3  0xb62bdfee in StressLog::LogMsg (level=4, facility=16384, cArgs=5, format=0xb6b85463 "Processing exception at establisher=%p, ip=%p disp->cxr: %p, sp: %p, cxr @ exception: %p\n")
    at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/utilcode/stresslog.cpp:669
#4  0xb64f1c04 in ProcessCLRException (pExceptionRecord=0xbeffe3ec, MemoryStackFp=3204443360, pContextRecord=0xbeffe440, pDispatcherContext=0xbeffdb58)
    at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/vm/exceptionhandling.cpp:770
#5  0xb64f7b94 in UnwindManagedExceptionPass1 (ex=..., frameContext=0xbeffddb8) at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/vm/exceptionhandling.cpp:4559
#6  0xb64f7fae in DispatchManagedException (ex=..., isHardwareException=true) at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/vm/exceptionhandling.cpp:4678
#7  0xb64efdf6 in HandleHardwareException (ex=0xbeffe3e0) at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/vm/exceptionhandling.cpp:5114
#8  0xb6a8fd3a in SEHProcessException (pointers=0xbeffe670) at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/pal/src/exception/seh.cpp:243
#9  0xb6a91972 in common_signal_handler (code=11, siginfo=0xbeffe938, sigcontext=0xbeffe9b8, numParams=2) at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/pal/src/exception/signal.cpp:597
#10 0xb6a90d94 in sigsegv_handler (code=11, siginfo=0xbeffe938, context=0xbeffe9b8) at /source/tizen_3.0/dotnet/coreclr_upstreaming/src/pal/src/exception/signal.cpp:266
#11 <signal handler called>
#12 0xb650b314 in JIT_WriteBarrier () at patchedcode.S:413
#13 0xb1adb8d6 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```
